/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sample_threading_activities_MasterActivity */

#ifndef _Included_com_sample_threading_activities_MasterActivity
#define _Included_com_sample_threading_activities_MasterActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sample_threading_activities_MasterActivity
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sample_threading_activities_MasterActivity_init
  (JNIEnv *, jobject);

/*
 * Class:     com_sample_threading_activities_MasterActivity
 * Method:    startThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sample_threading_activities_MasterActivity_startThread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
